### ISSUE TITLE
Add guideline about "Style at the lowest level element"

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-guidelines#3]
Because we don't control styles from the host of our emails, we might always end up with inheriting default styles from e‑mail clients, especially webmails. Thus a good practice is to always add relevant styles at the lowest level element.

Examples:

* Gmail and ul li
* SFR and h1, h2

**Comment by hteumeuleu** [comment]
Here’s an example from SFR webmail having the very loose CSS rule following:

```css
div.read-content-block :not(.userSignature *) {
  font: 100% "Helvetica Neue",Helvetica,Arial,sans-serif;
  margin: auto;
  padding: 0;
}
```

This forces a `font` reset to any element that doesn't have a font declaration inline.

![A screenshot of SFR webmail showing a loose CSS selector targeting * and applying a font reset.](https://github.com/hteumeuleu/email-guidelines/assets/3451753/1314b43e-67f6-44fb-8088-6ba43e8c237e)
